#include "configyyrename.h"

//#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[415] =
    {   0,
        1,    1,   47,   47,   51,   51,   55,   55,   60,   58,
        1,   45,   46,    2,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   59,   47,   48,   59,   49,   59,   54,   51,   52,
       53,   59,   55,   56,   57,   59,   58,    0,    1,    2,
        2,    2,    2,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   47,    0,   54,    0,   51,   55,    0,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   44,   58,   58,   58,
       58,   58,   58,   43,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   40,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,    4,
       58,   12,   58,   58,   21,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   31,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   24,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   35,   58,   58,   58,   58,   42,   58,    3,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   50,   58,
       58,   58,   58,   58,   13,   58,   58,   20,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   10,   58,   27,   58,   11,

       58,    8,    9,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   25,   58,   58,   28,   58,   32,
       26,   41,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   15,   58,   58,   30,   58,
       58,   58,   58,    6,   58,    5,   58,   58,   58,   58,
       58,   58,   58,   22,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   37,   34,   58,   58,   17,
       58,   58,   58,   33,    7,   58,   58,   36,   58,   14,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   18,   19,   58,   58,   58,   58,   58,   58,   16,

       58,   23,   58,   58,   58,   58,   58,   58,   58,   38,
       58,   39,   29,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    1,    1,    1,    1,    1,
        1,    8,    1,    9,    1,    1,    1,   10,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
        1,   36,    1,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    2,    3,    4,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[424] =
    {   0,
        0,    0,   59,   62,   66,   70,   73,   76, 1163, 1126,
       80, 1164, 1164,   83,   63,   71,   89,   75,   78,  101,
       81,  112,  102,  120,  109,  128,  115,  127,  138,  136,
      135,  182, 1124, 1164, 1164, 1164,   86, 1116, 1134, 1164,
     1164,  186, 1099, 1164, 1164,  156, 1098,  190,   91,    0,
      194,    0,    0,  172,  161,  173,  146,  168,  186,  191,
      196,  197,  209,  178,  203,  199,  205,  206,  214,  234,
      222,  228,  227,  241,  245,  236,  237,  250,  240,  256,
      248, 1095,  219, 1094,  294, 1125, 1088,  285,  271,  276,
      274,  278,  293,  275,  297,  300,  283,  208,  306,  301,

      309,  314,  249,  302,  310,  316,  320,  323,  331,  319,
      318,  327,  326,  333,  329,  361, 1087,  345,  358,  363,
      365,  349,  346, 1086,  364,  374,  372,  371,  384,  380,
      375,  381,  394,  398,  416,  417, 1080,  400,  415,  413,
      418,  414,  420,  422,  421,  426,  427,  444,  424,  448,
      447,  452,  465,  482,  454,  439,  442,  468,  475,  472,
      478,  476,  479,  480,  490,  502,  491,  507,  508, 1079,
      494, 1076,  504,  510, 1020,  520,  505,  516,  526,  514,
      534,  531,  528,  552,  538,  542,  546,  544,  989,  557,
      561,  554,  583,  567,  568,  563,  579,  571,  581,  593,

      578,  592,  597,  602,  607,  609,  620,  612,  610,  622,
      623,  613,  647,  624,  632,  640,  644,  648,  646,  649,
      650,  638,  651,  658,  671,  666,  676,  968,  680,  677,
      693,  678,  670,  699,  696,  683,  684,  687,  705,  712,
      697,  923,  721,  729,  633,  733,  922,  732,  890,  727,
      724,  722,  738,  740,  723,  730,  746,  756,  747,  753,
      748,  769,  761,  776,  777,  784,  767,  788,  888,  771,
      790,  791,  774,  786,  881,  793,  797,  828,  782,  799,
      795,  810,  801,  802,  815,  832,  814,  819,  834,  818,
      842,  843,  847,  836,  840,  773,  845,  720,  848,  706,

      852,  639,  637,  854,  859,  846,  858,  855,  871,  862,
      868,  889,  893,  872,  605,  895,  898,  545,  883,  501,
      450,  411,  903,  896,  904,  891,  906,  908,  915,  894,
      897,  918,  921,  927,  913,  401,  939,  924,  397,  941,
      949,  948,  931,  391,  947,  390,  953,  961,  932,  957,
      951,  963,  959,  357,  958,  990,  994,  986,  996,  993,
      995,  974,  980, 1001,  998,  356,  335, 1007,  988,  288,
      991, 1000, 1002,  284,  267, 1006, 1025,  221, 1021,  177,
     1027, 1032, 1031, 1033, 1043, 1045, 1046, 1029, 1037, 1055,
     1059,  171,  140, 1053, 1050, 1057, 1065, 1072, 1074,  132,

     1068,  110, 1081, 1085, 1069, 1083, 1092, 1078, 1096,   99,
     1101,   97,   85, 1164, 1137, 1141, 1145,  112, 1149, 1153,
       82, 1155, 1157
    } ;

static yyconst flex_int16_t yy_def[424] =
    {   0,
      414,    1,  415,  415,  416,  416,  417,  417,  414,  418,
      414,  414,  414,  419,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  420,  414,  414,  414,  420,  421,  414,  414,
      414,  421,  422,  414,  414,  422,  418,  418,  414,  423,
      419,  423,  419,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  420,  420,  421,  421,  414,  422,  422,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,    0,  414,  414,  414,  414,  414,  414,
      414,  414,  414
    } ;

static yyconst flex_int16_t yy_nxt[1226] =
    {   0,
       10,   11,   12,   12,   13,   14,   10,   10,   10,   10,
       15,   10,   16,   17,   10,   10,   10,   18,   19,   20,
       21,   10,   22,   23,   24,   10,   25,   26,   27,   28,
       29,   10,   30,   10,   31,   32,   15,   10,   16,   17,
       10,   10,   10,   18,   19,   20,   21,   10,   22,   23,
       24,   10,   25,   26,   27,   28,   29,   10,   30,   10,
       31,   34,   35,   36,   34,   35,   36,   39,   40,   40,
       41,   39,   40,   40,   41,   44,   44,   45,   44,   44,
       45,   49,   84,   54,   52,   50,   52,   52,   56,   82,
       82,   61,   49,   60,   37,   55,   50,   37,   48,   57,

       62,   42,   63,   58,   65,   42,   48,   59,   46,   54,
       48,   46,   47,   48,   56,   64,   48,   61,   53,   60,
       48,   55,   66,   73,   48,   57,   62,   76,   63,   58,
       65,   69,   48,   59,   48,   67,   48,   48,   70,   68,
       77,   64,   74,   71,   48,   48,   72,   48,   66,   73,
       48,   80,   79,   76,   78,   48,   75,   69,   81,   87,
       87,   67,   48,   48,   70,   68,   77,   48,   74,   71,
       48,   48,   72,   48,   93,   48,   91,   80,   79,   94,
       78,   48,   75,   47,   81,   47,   47,   84,   89,   84,
       84,   47,   90,   47,   47,   52,   48,   52,   52,   92,

       93,   95,   91,   48,   96,   94,   48,   48,   48,   98,
       97,  103,   48,   48,   89,   99,  100,  101,   90,  104,
      105,   48,   82,   82,  107,   92,   48,   95,  131,   53,
       96,   48,   48,  106,   48,   98,   97,  103,   48,  102,
       48,   48,  108,   48,   48,  104,  105,  109,  110,   48,
      107,  111,  112,  113,  131,  115,   48,   48,  137,  106,
      116,  117,   48,   48,  118,  102,  119,  114,  108,   48,
      121,   48,   48,  109,  110,   48,   48,  111,  112,  113,
       48,  115,  120,   48,   48,   48,  116,  117,   87,   87,
      118,   48,  119,  114,  122,   84,  121,   84,   84,  123,

      124,  125,   48,  126,  127,  130,   48,  133,  120,   48,
       48,   48,  128,   48,  129,  134,  132,  138,   48,   48,
      122,  135,  136,   48,  139,  123,  124,  125,   48,  126,
      127,  130,   48,  141,  140,   48,   48,   48,  128,  142,
      129,   48,  132,  138,   48,   48,  143,  144,  145,   48,
      139,   48,  147,   48,   48,   48,  146,  149,   48,  141,
      140,   48,   48,  148,   48,  142,   48,  150,   48,  152,
       48,  151,  143,  144,  145,  155,  153,  156,  147,  154,
       48,   48,  146,  149,   48,  158,  160,  157,  159,  148,
      161,   48,   48,   48,  164,  152,   48,  151,   48,   48,

       48,  155,  153,  156,  163,  154,   48,   48,  162,   48,
       48,  158,  160,  157,  159,   48,   48,  165,  169,   48,
      164,  166,  167,  168,  170,   48,   48,  172,  171,   48,
      163,  175,   48,   48,  162,   48,   48,  173,  174,  176,
      177,  178,  180,  165,  169,  193,   48,  166,   48,   48,
       48,   48,   48,   48,  171,   48,   48,   48,  179,   48,
      181,   48,   48,  173,  174,  176,  177,  178,  180,  184,
      194,  186,  192,  182,   48,  185,  183,   48,  195,   48,
      187,  196,   48,   48,  179,   48,  181,   48,  188,   48,
      197,  189,  200,  201,  199,  184,  194,  190,  192,  182,

       48,  185,  183,   48,  195,  204,  187,   48,  198,  191,
       48,   48,  202,   48,   48,   48,  197,   48,  200,  201,
      199,  205,  208,  190,  203,   48,   48,  207,  206,   48,
      209,  204,  211,  210,  198,  191,   48,   48,  202,   48,
       48,  214,   48,   48,  212,   48,  217,  205,  208,   48,
      203,   48,  213,  207,  206,   48,  209,  215,  211,  210,
      216,   48,  218,   48,  221,  219,   48,  214,  220,   48,
      212,  222,  217,   48,  224,  223,  228,   48,  213,   48,
       48,   48,  225,  215,  230,  232,  216,   48,  218,   48,
      221,  219,   48,  226,  220,  229,   48,  222,   48,  231,

      224,  223,   48,   48,  235,  227,   48,  234,  225,  233,
      230,  232,  236,   48,   48,  238,   48,  237,   48,  226,
      239,  229,  247,  240,  244,  231,  241,   48,   48,  242,
      235,  227,   48,  234,  243,  233,  245,   48,  236,  279,
       48,  238,   48,  237,   48,   48,  239,   48,   48,  240,
      244,  246,  250,  248,  252,   48,  249,   48,   48,   48,
      243,  251,  245,  256,  255,  253,  258,   48,   48,  254,
      257,  259,   48,   48,   48,   48,  260,  246,  250,   48,
      252,   48,   48,   48,   48,   48,   48,  251,  261,  256,
      255,  253,  258,   48,  264,  254,  257,  259,  262,  263,

      265,   48,  260,  268,  267,   48,   48,  266,  269,  273,
      270,   48,   48,   48,  261,   48,  271,  272,   48,   48,
      264,  275,   48,  276,  262,  263,  265,  274,   48,  268,
      267,   48,   48,  266,   48,  273,  270,  277,  278,  280,
       48,   48,  271,  272,  281,  282,  283,   48,  284,  276,
      288,  287,  285,  274,  286,   48,   48,   48,   48,   48,
      289,  291,   48,  277,   48,   48,  290,   48,   48,  293,
      281,  282,  283,   48,  284,   48,  288,  287,  285,  292,
      286,   48,   48,   48,  294,  296,  289,  291,   48,  295,
      297,   48,  290,  298,  299,  293,   48,  300,  301,  302,

      303,  304,   48,  307,   48,  292,   48,  306,   48,   48,
      294,   48,   48,  305,  308,  295,  297,   48,  310,   48,
      299,   48,  311,   48,  301,   48,   48,  304,   48,  312,
       48,  309,   48,  306,   48,  313,   48,   48,  314,  305,
      308,  315,  317,  318,  310,   48,  319,  316,  311,   48,
       48,  320,  321,   48,   48,  312,  322,  309,  324,  325,
      328,  313,  323,   48,  314,  329,  326,   48,  317,   48,
      332,   48,  319,  316,  330,   48,  331,   48,   48,  327,
       48,   48,   48,   48,  324,  325,  333,   48,  323,   48,
       48,  334,  326,   48,   48,  335,  332,   48,  336,  337,

      330,  338,  331,   48,  339,  327,   48,   48,  340,  342,
      341,  343,  333,  344,  345,  346,   48,  334,   48,  350,
      349,  335,  354,   48,   48,   48,   48,  338,   48,   48,
       48,   48,   48,   48,  340,  347,  341,  343,   48,   48,
      345,   48,  348,   48,  351,  350,  349,  352,   48,  353,
       48,  355,  356,   48,  357,  358,   48,   48,   48,   48,
      366,  347,   48,  359,  360,  364,   48,   48,  348,  361,
      351,  362,  367,  352,   48,  353,   48,  355,  356,  363,
      357,  369,   48,   48,   48,  365,   48,  368,   48,  359,
      360,  364,   48,   48,   48,  361,   48,  362,   48,  370,

      371,  372,  374,   48,  375,  363,  373,  369,  376,   48,
      378,  365,  379,  368,  377,   48,  380,  381,  383,  382,
      385,   48,  384,   48,   48,   48,   48,  372,   48,   48,
       48,   48,  373,   48,  376,   48,   48,   48,  379,  386,
      377,   48,   48,  381,  383,  382,  385,  387,  384,  388,
      389,  390,  392,  391,  393,   48,   48,  395,  396,  400,
       48,  394,   48,  399,   48,  386,   48,   48,   48,  397,
      398,  401,   48,  387,  402,  388,  389,  390,   48,  391,
       48,   48,  403,  395,  396,   48,  404,  394,   48,  399,
       48,  405,   48,  406,   48,  397,  398,  401,  408,  407,

       48,  410,  409,   48,   48,  412,  411,   48,  403,   48,
      413,   48,  404,   48,   48,   48,   48,  405,   48,  406,
       48,   48,   48,   88,  408,  407,   86,   48,  409,   85,
       83,   48,  411,   48,   88,   86,   48,   33,   33,   33,
       33,   38,   38,   38,   38,   43,   43,   43,   43,   51,
       51,   85,   51,   82,   82,   87,   87,   52,   52,   83,
       52,   48,  414,    9,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414
    } ;

static yyconst flex_int16_t yy_chk[1226] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    4,    4,    4,    5,    5,    5,
        5,    6,    6,    6,    6,    7,    7,    7,    8,    8,
        8,   11,  421,   15,   14,   11,   14,   14,   16,   37,
       37,   19,   49,   18,    3,   15,   49,    4,   15,   17,

       19,    5,   19,   17,   21,    6,   16,   17,    7,   15,
       18,    8,  418,   19,   16,   20,   21,   19,   14,   18,
      413,   15,   22,   25,   17,   17,   19,   27,   19,   17,
       21,   23,  412,   17,  410,   22,   20,   23,   24,   22,
       28,   20,   26,   24,   25,  402,   24,   22,   22,   25,
       27,   30,   29,   27,   28,   24,   26,   23,   31,   46,
       46,   22,   28,   26,   24,   22,   28,  400,   26,   24,
       31,   30,   24,   29,   57,  393,   55,   30,   29,   58,
       28,   57,   26,   32,   31,   32,   32,   42,   54,   42,
       42,   48,   54,   48,   48,   51,   55,   51,   51,   56,

       57,   59,   55,   58,   60,   58,  392,   54,   56,   62,
       61,   64,  380,   64,   54,   63,   63,   63,   54,   65,
       66,   59,   83,   83,   68,   56,   60,   59,   98,   51,
       60,   61,   62,   67,   66,   62,   61,   64,   65,   63,
       67,   68,   69,   98,   63,   65,   66,   70,   71,   69,
       68,   72,   73,   74,   98,   75,  378,   71,  103,   67,
       76,   77,   73,   72,   78,   63,   79,   74,   69,   70,
       81,   76,   77,   70,   71,   79,   74,   72,   73,   74,
       75,   75,   80,   81,  103,   78,   76,   77,   88,   88,
       78,   80,   79,   74,   89,   85,   81,   85,   85,   90,

       91,   92,  375,   93,   94,   97,   89,  100,   80,   91,
       94,   90,   95,   92,   96,  101,   99,  104,   97,  374,
       89,  102,  102,  370,  105,   90,   91,   92,   93,   93,
       94,   97,   95,  107,  106,   96,  100,  104,   95,  108,
       96,   99,   99,  104,  101,  105,  109,  110,  111,  102,
      105,  106,  113,  111,  110,  107,  112,  115,  108,  107,
      106,  113,  112,  114,  115,  108,  109,  116,  114,  119,
      367,  118,  109,  110,  111,  122,  120,  123,  113,  121,
      118,  123,  112,  115,  122,  126,  128,  125,  127,  114,
      129,  366,  354,  119,  132,  119,  116,  118,  120,  125,

      121,  122,  120,  123,  131,  121,  128,  127,  130,  126,
      131,  126,  128,  125,  127,  130,  132,  133,  138,  129,
      132,  134,  135,  136,  139,  346,  344,  141,  140,  133,
      131,  144,  339,  134,  130,  138,  336,  142,  143,  145,
      146,  147,  149,  133,  138,  156,  322,  134,  140,  142,
      139,  135,  136,  141,  140,  143,  145,  144,  148,  149,
      150,  146,  147,  142,  143,  145,  146,  147,  149,  151,
      157,  153,  155,  150,  156,  152,  150,  157,  158,  148,
      153,  159,  151,  150,  148,  321,  150,  152,  154,  155,
      160,  154,  163,  164,  162,  151,  157,  154,  155,  150,

      153,  152,  150,  158,  158,  167,  153,  160,  161,  154,
      159,  162,  165,  161,  163,  164,  160,  154,  163,  164,
      162,  168,  173,  154,  166,  165,  167,  171,  169,  171,
      174,  167,  177,  176,  161,  154,  320,  166,  165,  173,
      177,  180,  168,  169,  178,  174,  183,  168,  173,  180,
      166,  178,  179,  171,  169,  176,  174,  181,  177,  176,
      182,  179,  184,  183,  187,  185,  182,  180,  186,  181,
      178,  188,  183,  185,  191,  190,  194,  186,  179,  188,
      318,  187,  192,  181,  196,  198,  182,  184,  184,  192,
      187,  185,  190,  193,  186,  195,  191,  188,  196,  197,

      191,  190,  194,  195,  201,  193,  198,  200,  192,  199,
      196,  198,  202,  201,  197,  204,  199,  203,  193,  193,
      205,  195,  212,  206,  209,  197,  207,  202,  200,  207,
      201,  193,  203,  200,  208,  199,  210,  204,  202,  245,
      315,  204,  205,  203,  206,  209,  205,  208,  212,  206,
      209,  211,  214,  213,  216,  207,  213,  210,  211,  214,
      208,  215,  210,  220,  219,  217,  222,  215,  245,  218,
      221,  223,  303,  222,  302,  216,  224,  211,  214,  217,
      216,  219,  213,  218,  220,  221,  223,  215,  225,  220,
      219,  217,  222,  224,  229,  218,  221,  223,  226,  227,

      230,  226,  224,  233,  232,  233,  225,  231,  234,  238,
      235,  227,  230,  232,  225,  229,  236,  237,  236,  237,
      229,  240,  238,  241,  226,  227,  230,  239,  231,  233,
      232,  235,  241,  231,  234,  238,  235,  243,  244,  246,
      239,  300,  236,  237,  248,  250,  251,  240,  252,  241,
      256,  255,  253,  239,  254,  298,  243,  252,  255,  251,
      257,  259,  250,  243,  244,  256,  258,  248,  246,  261,
      248,  250,  251,  253,  252,  254,  256,  255,  253,  260,
      254,  257,  259,  261,  262,  264,  257,  259,  260,  263,
      265,  258,  258,  266,  267,  261,  263,  268,  270,  271,

      272,  273,  267,  277,  262,  260,  270,  276,  296,  273,
      262,  264,  265,  274,  279,  263,  265,  279,  281,  266,
      267,  274,  282,  268,  270,  271,  272,  273,  276,  283,
      281,  280,  277,  276,  280,  284,  283,  284,  285,  274,
      279,  286,  288,  289,  281,  282,  290,  287,  282,  287,
      285,  291,  292,  290,  288,  283,  293,  280,  295,  297,
      304,  284,  294,  278,  285,  305,  299,  286,  288,  289,
      308,  294,  290,  287,  306,  295,  307,  291,  292,  301,
      297,  306,  293,  299,  295,  297,  309,  301,  294,  304,
      308,  310,  299,  307,  305,  311,  308,  310,  312,  313,

      306,  314,  307,  311,  316,  301,  309,  314,  317,  323,
      319,  324,  309,  325,  326,  327,  275,  310,  319,  331,
      330,  311,  335,  269,  312,  249,  326,  314,  313,  330,
      316,  324,  331,  317,  317,  328,  319,  324,  323,  325,
      326,  327,  329,  328,  332,  331,  330,  333,  335,  334,
      329,  337,  338,  332,  340,  341,  333,  247,  242,  338,
      351,  328,  334,  342,  343,  349,  343,  349,  329,  345,
      332,  347,  352,  333,  337,  334,  340,  337,  338,  348,
      340,  355,  345,  342,  341,  350,  351,  353,  347,  342,
      343,  349,  350,  355,  353,  345,  348,  347,  352,  356,

      357,  358,  360,  228,  361,  348,  359,  355,  362,  362,
      364,  350,  365,  353,  363,  363,  368,  369,  372,  371,
      376,  358,  373,  369,  189,  356,  371,  358,  360,  357,
      361,  359,  359,  365,  362,  372,  364,  373,  365,  377,
      363,  376,  368,  369,  372,  371,  376,  379,  373,  381,
      382,  383,  385,  384,  386,  175,  379,  388,  389,  395,
      377,  387,  381,  394,  388,  377,  383,  382,  384,  390,
      391,  396,  389,  379,  397,  381,  382,  383,  385,  384,
      386,  387,  398,  388,  389,  395,  399,  387,  394,  394,
      390,  401,  396,  403,  391,  390,  391,  396,  405,  404,

      397,  407,  406,  401,  405,  409,  408,  398,  398,  399,
      411,  172,  399,  408,  170,  137,  403,  401,  406,  403,
      404,  124,  117,   87,  405,  404,   86,  407,  406,   84,
       82,  409,  408,   47,   43,   39,  411,  415,  415,  415,
      415,  416,  416,  416,  416,  417,  417,  417,  417,  419,
      419,   38,  419,  420,  420,  422,  422,  423,  423,   33,
      423,   10,    9,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;


/*
 * configlexer.lex - lexical analyzer for NSD config file
 *
 * Copyright (c) 2001-2011, NLnet Labs. All rights reserved
 *
 * See LICENSE for the license.
 *
 */

#include "config.h"

#include <ctype.h>
#include <errno.h>
#include <string.h>
#include <strings.h>

#include "options.h"
#include "configyyrename.h"
#include "configparser.h"
void c_error(const char *message);

#define YY_NO_UNPUT

#if 0
#define LEXOUT(s)  printf s /* used ONLY when debugging */
#else
#define LEXOUT(s)
#endif

struct inc_state {
	const char* filename;
	int line;
};
static struct inc_state parse_stack[MAXINCLUDES];
static YY_BUFFER_STATE include_stack[MAXINCLUDES];
static int config_include_stack_ptr = 0;

static void config_start_include(const char* filename)
{
	FILE *input;
	if(strlen(filename) == 0) {
		c_error_msg("empty include file name");
		return;
	}
	if(config_include_stack_ptr >= MAXINCLUDES) {
		c_error_msg("includes nested too deeply, skipped (>%d)", MAXINCLUDES);
		return;
	}
	input = fopen(filename, "r");
	if(!input) {
		c_error_msg("cannot open include file '%s': %s",
			filename, strerror(errno));
		return;
	}
	LEXOUT(("switch_to_include_file(%s) ", filename));
	parse_stack[config_include_stack_ptr].filename = cfg_parser->filename;
	parse_stack[config_include_stack_ptr].line = cfg_parser->line;
	include_stack[config_include_stack_ptr] = YY_CURRENT_BUFFER;
	cfg_parser->filename = region_strdup(cfg_parser->opt->region, filename);
	cfg_parser->line = 1;
	yy_switch_to_buffer(yy_create_buffer(input,YY_BUF_SIZE));
	++config_include_stack_ptr;
}

static void config_end_include(void)
{
	--config_include_stack_ptr;
	cfg_parser->filename = parse_stack[config_include_stack_ptr].filename;
	cfg_parser->line = parse_stack[config_include_stack_ptr].line;
	yy_delete_buffer(YY_CURRENT_BUFFER);
	yy_switch_to_buffer(include_stack[config_include_stack_ptr]);
}

#ifndef yy_set_bol /* compat definition, for flex 2.4.6 */
#define yy_set_bol(at_bol) \
        { \
	        if ( ! yy_current_buffer ) \
	                yy_current_buffer = yy_create_buffer(yyin,YY_BUF_SIZE ); \
	        yy_current_buffer->yy_ch_buf[0] = ((at_bol)?'\n':' '); \
        }
#endif


//#line 956 "<stdout>"

#define INITIAL 0
#define quotedstring 1
#define include 2
#define include_quoted 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    


	//#line 1148 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 415 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1164 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP

{ LEXOUT(("SP ")); /* ignore */ }
	YY_BREAK
case 2:
YY_RULE_SETUP

{ LEXOUT(("comment(%s) ", yytext)); /* ignore */ }
	YY_BREAK
case 3:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_SERVER;}
	YY_BREAK
case 4:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_NAME;}
	YY_BREAK
case 5:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IP_ADDRESS;}
	YY_BREAK
case 6:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_DEBUG_MODE;}
	YY_BREAK
case 7:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_HIDE_VERSION;}
	YY_BREAK
case 8:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IP4_ONLY;}
	YY_BREAK
case 9:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IP6_ONLY;}
	YY_BREAK
case 10:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_DATABASE;}
	YY_BREAK
case 11:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IDENTITY;}
	YY_BREAK
case 12:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_NSID;}
	YY_BREAK
case 13:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_LOGFILE;}
	YY_BREAK
case 14:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_SERVER_COUNT;}
	YY_BREAK
case 15:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_TCP_COUNT;}
	YY_BREAK
case 16:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_TCP_QUERY_COUNT;}
	YY_BREAK
case 17:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_TCP_TIMEOUT;}
	YY_BREAK
case 18:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IPV4_EDNS_SIZE;}
	YY_BREAK
case 19:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_IPV6_EDNS_SIZE;}
	YY_BREAK
case 20:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_PIDFILE;}
	YY_BREAK
case 21:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_PORT;}
	YY_BREAK
case 22:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_STATISTICS;}
	YY_BREAK
case 23:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ZONESTATSFILE;}
	YY_BREAK
case 24:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_CHROOT;}
	YY_BREAK
case 25:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_USERNAME;}
	YY_BREAK
case 26:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ZONESDIR;}
	YY_BREAK
case 27:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_DIFFFILE;}
	YY_BREAK
case 28:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_XFRDFILE;}
	YY_BREAK
case 29:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_XFRD_RELOAD_TIMEOUT;}
	YY_BREAK
case 30:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_VERBOSITY;}
	YY_BREAK
case 31:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ZONE;}
	YY_BREAK
case 32:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ZONEFILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ALLOW_NOTIFY;}
	YY_BREAK
case 34:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_REQUEST_XFR;}
	YY_BREAK
case 35:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_NOTIFY;}
	YY_BREAK
case 36:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_NOTIFY_RETRY;}
	YY_BREAK
case 37:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_PROVIDE_XFR;}
	YY_BREAK
case 38:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_OUTGOING_INTERFACE;}
	YY_BREAK
case 39:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ALLOW_AXFR_FALLBACK;}
	YY_BREAK
case 40:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_KEY;}
	YY_BREAK
case 41:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_ALGORITHM;}
	YY_BREAK
case 42:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_SECRET;}
	YY_BREAK
case 43:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_AXFR;}
	YY_BREAK
case 44:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); return VAR_UDP;}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP

{ LEXOUT(("NL\n")); cfg_parser->line++;}
	YY_BREAK
/* Quoted strings. Strip leading and ending quotes */
case 46:
YY_RULE_SETUP

{ BEGIN(quotedstring); LEXOUT(("QS ")); }
	YY_BREAK
case YY_STATE_EOF(quotedstring):

{
        yyerror("EOF inside quoted string");
        BEGIN(INITIAL);
}
	YY_BREAK
case 47:
YY_RULE_SETUP

{ LEXOUT(("STR(%s) ", yytext)); yymore(); }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP

{ cfg_parser->line++; yymore(); }
	YY_BREAK
case 49:
YY_RULE_SETUP

{
        LEXOUT(("QE "));
        BEGIN(INITIAL);
        yytext[yyleng - 1] = '\0';
	yylval.str = region_strdup(cfg_parser->opt->region, yytext);
        return STRING;
}
	YY_BREAK
/* include: directive */
case 50:
YY_RULE_SETUP

{ LEXOUT(("v(%s) ", yytext)); BEGIN(include); }
	YY_BREAK
case YY_STATE_EOF(include):

{
        yyerror("EOF inside include directive");
        BEGIN(INITIAL);
}
	YY_BREAK
case 51:
YY_RULE_SETUP

{ LEXOUT(("ISP ")); /* ignore */ }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP

{ LEXOUT(("NL\n")); cfg_parser->line++;}
	YY_BREAK
case 53:
YY_RULE_SETUP

{ LEXOUT(("IQS ")); BEGIN(include_quoted); }
	YY_BREAK
case 54:
YY_RULE_SETUP

{
	LEXOUT(("Iunquotedstr(%s) ", yytext));
	config_start_include(yytext);
	BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(include_quoted):

{
        yyerror("EOF inside quoted string");
        BEGIN(INITIAL);
}
	YY_BREAK
case 55:
YY_RULE_SETUP

{ LEXOUT(("ISTR(%s) ", yytext)); yymore(); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP

{ cfg_parser->line++; yymore(); }
	YY_BREAK
case 57:
YY_RULE_SETUP

{
	LEXOUT(("IQE "));
	yytext[yyleng - 1] = '\0';
	config_start_include(yytext);
	BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):

{
	yy_set_bol(1); /* Set beginning of line, so "^" rules match.  */
	if (config_include_stack_ptr == 0) {
		yyterminate();
	} else {
		fclose(yyin);
		config_end_include();
	}
}
	YY_BREAK
case 58:
YY_RULE_SETUP

{ LEXOUT(("unquotedstr(%s) ", yytext)); 
			yylval.str = region_strdup(cfg_parser->opt->region, yytext); return STRING; }
	YY_BREAK
case 59:
YY_RULE_SETUP

ECHO;
	YY_BREAK
	  //#line 1587 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 415 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 415 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 414);

	return yy_is_jam ? 0 : yy_current_state;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"





